use_frameworks!

target 'Slider_Example' do
  pod 'Slider', :path => '../'

  target 'Slider_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
